version: '3'
services:
  hub:
    image: selenium/hub:4.8.3
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:4.8.3
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  firefox:
    image: selenium/node-firefox:4.8.3
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  search-module:
    image: dockps/selenium-docker
    shm_size: '2gb'
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - SE_EVENT_BUS_HOST=hub
      - MODULE=search-module.xml
    volumes:
      - ./search-result:/usr/share/udemy/test-output

  